using System.Collections.Generic;
using System.IO;
using System.Xml;
using UnityEditor;
using UnityEditor.Android;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.SceneManagement;
using UnityEditor.XR.ARCore;
using UnityEditor.XR.Management;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;
using UnityEngine.XR.ARCore;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.Management;

/// <summary>
/// Validates the Android AR build contract needed for the mobile client camera background prototype.
/// </summary>
public sealed class SUN_SV_AndroidARBuildValidator : IPreprocessBuildWithReport, IPostGenerateGradleAndroidProject
{
    private const string AndroidXmlNamespace = "http://schemas.android.com/apk/res/android";
    private const string FallbackScenePath = "Assets/Scenes/SampleScene.unity";
    private const string StandardCameraTestScenePath = "Assets/Scenes/ARCameraTest.unity";
    private const string XRGeneralSettingsPerBuildTargetPath = "Assets/XR/XRGeneralSettingsPerBuildTarget.asset";
    private const string MobileRenderPipelineAssetPath = "Assets/Settings/Mobile_RPAsset.asset";
    private const string MobileRendererDataPath = "Assets/Settings/Mobile_Renderer.asset";
    private const string MainCameraName = "Main Camera";
    private const string GeneratedManifestRelativePath = "src/main/AndroidManifest.xml";
    private const string AndroidPermissionCamera = "android.permission.CAMERA";
    private const string AndroidHardwareCameraAr = "android.hardware.camera.ar";
    private const string GoogleArCoreMetaDataName = "com.google.ar.core";
    private const string SkipPermissionsDialogMetaDataName = "unityplayer.SkipPermissionsDialog";

    public int callbackOrder => 100;

    public void OnPreprocessBuild(BuildReport report)
    {
        if (report.summary.platform != BuildTarget.Android)
        {
            return;
        }

        NormalizeAndroidARBuildContract();

        List<string> errors = new List<string>();
        ValidateAndroidXRLoader(errors);
        ValidateARCoreSettings(errors);
        ValidateAndroidApplicationEntry(errors);
        ValidateAndroidGraphicsSettings(errors);
        ValidateAndroidOrientationSettings(errors);
        ValidateMobileRenderPipelineAsset(errors);
        ValidateMobileRendererFeatures(errors);
        ValidateMobileARCameraSceneSettings(errors);

        if (errors.Count > 0)
        {
            throw new BuildFailedException(
                $"{nameof(SUN_SV_AndroidARBuildValidator)} blocked Android build because the mobile AR camera contract is incomplete:\n- " +
                string.Join("\n- ", errors));
        }

        Debug.Log(
            $"{nameof(SUN_SV_AndroidARBuildValidator)} verified Android AR build prerequisites. " +
            "ARCoreLoader is active, ARCore is Required, CAMERA/ARCore manifest entries will be generated by the ARCore build processor, " +
            "Android uses the standard Activity entry point and OpenGLES3 for the camera feed, the app is locked to Landscape Left during AR camera validation, " +
            "and URP/AR camera settings use a simple no-HDR/no-MSAA/no-post-processing background path.");
    }

    private static void NormalizeAndroidARBuildContract()
    {
        bool changedPlayerSettings = NormalizeAndroidApplicationEntry();
        changedPlayerSettings |= NormalizeAndroidOrientationSettings();
        bool changedPipelineAsset = NormalizeMobileRenderPipelineAsset();
        bool changedRendererData = NormalizeMobileRendererSettings();
        bool changedScene = NormalizeMobileARCameraSceneSettings();

        if (changedPlayerSettings || changedPipelineAsset || changedRendererData || changedScene)
        {
            AssetDatabase.SaveAssets();
            Debug.Log(
                $"{nameof(SUN_SV_AndroidARBuildValidator)} normalized Android AR build settings before validation. " +
                "This keeps an already-open Unity Editor scene or PlayerSettings memory state aligned with the saved landscape/no-HDR/no-MSAA AR camera contract.");
        }
    }

    private static bool NormalizeAndroidApplicationEntry()
    {
        // Android XR/OpenXR용 GameActivity에서는 일부 휴대폰의 ARCore 센서 큐 생성이 실패할 수 있다.
        // 이 모바일 ARCore 검증 빌드는 표준 Activity 진입점을 사용해 카메라/센서 생명주기를 연결한다.
        return SetPlayerSettingIfDifferent(
            PlayerSettings.Android.applicationEntry != AndroidApplicationEntry.Activity,
            () => PlayerSettings.Android.applicationEntry = AndroidApplicationEntry.Activity);
    }

    private static bool NormalizeAndroidOrientationSettings()
    {
        bool changed = false;
        changed |= SetPlayerSettingIfDifferent(
            PlayerSettings.defaultInterfaceOrientation != UIOrientation.LandscapeLeft,
            () => PlayerSettings.defaultInterfaceOrientation = UIOrientation.LandscapeLeft);
        changed |= SetPlayerSettingIfDifferent(
            PlayerSettings.allowedAutorotateToPortrait,
            () => PlayerSettings.allowedAutorotateToPortrait = false);
        changed |= SetPlayerSettingIfDifferent(
            PlayerSettings.allowedAutorotateToPortraitUpsideDown,
            () => PlayerSettings.allowedAutorotateToPortraitUpsideDown = false);
        changed |= SetPlayerSettingIfDifferent(
            !PlayerSettings.allowedAutorotateToLandscapeLeft,
            () => PlayerSettings.allowedAutorotateToLandscapeLeft = true);
        changed |= SetPlayerSettingIfDifferent(
            PlayerSettings.allowedAutorotateToLandscapeRight,
            () => PlayerSettings.allowedAutorotateToLandscapeRight = false);

        return changed;
    }

    private static bool NormalizeMobileRenderPipelineAsset()
    {
        UniversalRenderPipelineAsset pipelineAsset = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(MobileRenderPipelineAssetPath);
        if (pipelineAsset == null)
        {
            return false;
        }

        bool changed = false;
        changed |= SetIfDifferent(pipelineAsset.supportsHDR, value => pipelineAsset.supportsHDR = value, false);
        changed |= SetIfDifferent(pipelineAsset.msaaSampleCount, value => pipelineAsset.msaaSampleCount = value, 1);
        changed |= SetIfDifferent(pipelineAsset.renderScale, value => pipelineAsset.renderScale = value, 1.0f);
        changed |= SetIfDifferent(pipelineAsset.supportsCameraDepthTexture, value => pipelineAsset.supportsCameraDepthTexture = value, false);
        changed |= SetIfDifferent(pipelineAsset.supportsCameraOpaqueTexture, value => pipelineAsset.supportsCameraOpaqueTexture = value, false);

        if (changed)
        {
            EditorUtility.SetDirty(pipelineAsset);
        }

        return changed;
    }

    private static bool NormalizeMobileRendererSettings()
    {
        ScriptableRendererData rendererData = AssetDatabase.LoadAssetAtPath<ScriptableRendererData>(MobileRendererDataPath);
        if (rendererData == null || !rendererData.useNativeRenderPass)
        {
            return false;
        }

        rendererData.useNativeRenderPass = false;
        EditorUtility.SetDirty(rendererData);
        return true;
    }

    private static bool NormalizeMobileARCameraSceneSettings()
    {
        string scenePath = GetValidationScenePath();
        Scene alreadyLoadedScene = SceneManager.GetSceneByPath(scenePath);
        bool wasSceneAlreadyLoaded = alreadyLoadedScene.IsValid() && alreadyLoadedScene.isLoaded;
        Scene scene = wasSceneAlreadyLoaded ? alreadyLoadedScene : EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Additive);
        bool changed = false;

        try
        {
            Camera arCamera = FindSceneCamera(scene, MainCameraName);
            if (arCamera == null)
            {
                return false;
            }

            changed |= SetIfDifferent(arCamera.allowHDR, value => arCamera.allowHDR = value, false);
            changed |= SetIfDifferent(arCamera.allowMSAA, value => arCamera.allowMSAA = value, false);
            changed |= SetIfDifferent(arCamera.allowDynamicResolution, value => arCamera.allowDynamicResolution = value, false);
            changed |= SetIfDifferent(arCamera.targetTexture != null, () => arCamera.targetTexture = null);
            changed |= SetIfDifferent(!IsFullScreenRect(arCamera.rect), () => arCamera.rect = new Rect(0.0f, 0.0f, 1.0f, 1.0f));

            UniversalAdditionalCameraData cameraData = arCamera.GetComponent<UniversalAdditionalCameraData>();
            if (cameraData == null)
            {
                cameraData = arCamera.gameObject.AddComponent<UniversalAdditionalCameraData>();
                changed = true;
            }

            changed |= NormalizeUniversalAdditionalCameraData(cameraData);

            if (changed)
            {
                EditorUtility.SetDirty(arCamera);
                EditorSceneManager.MarkSceneDirty(scene);
                if (!wasSceneAlreadyLoaded)
                {
                    EditorSceneManager.SaveScene(scene);
                }
            }
        }
        finally
        {
            if (!wasSceneAlreadyLoaded && scene.IsValid())
            {
                EditorSceneManager.CloseScene(scene, true);
            }
        }

        return changed;
    }

    private static bool NormalizeUniversalAdditionalCameraData(UniversalAdditionalCameraData cameraData)
    {
        bool changed = false;

        changed |= SetIfDifferent(cameraData.renderType, value => cameraData.renderType = value, CameraRenderType.Base);

        List<Camera> cameraStack = cameraData.cameraStack;
        if (cameraStack != null && cameraStack.Count > 0)
        {
            cameraStack.Clear();
            changed = true;
        }

        changed |= SetIfDifferent(cameraData.renderPostProcessing, value => cameraData.renderPostProcessing = value, false);
        changed |= SetIfDifferent(cameraData.antialiasing, value => cameraData.antialiasing = value, AntialiasingMode.None);
        changed |= SetIfDifferent(cameraData.allowHDROutput, value => cameraData.allowHDROutput = value, false);
        changed |= SetIfDifferent(cameraData.requiresDepthTexture, value => cameraData.requiresDepthTexture = value, false);
        changed |= SetIfDifferent(cameraData.requiresColorTexture, value => cameraData.requiresColorTexture = value, false);

        if (changed)
        {
            EditorUtility.SetDirty(cameraData);
        }

        return changed;
    }

    private static bool SetIfDifferent<T>(T currentValue, System.Action<T> setValue, T expectedValue)
    {
        if (EqualityComparer<T>.Default.Equals(currentValue, expectedValue))
        {
            return false;
        }

        setValue(expectedValue);
        return true;
    }

    private static bool SetIfDifferent(bool shouldSet, System.Action setValue)
    {
        if (!shouldSet)
        {
            return false;
        }

        setValue();
        return true;
    }

    private static bool SetPlayerSettingIfDifferent(bool shouldSet, System.Action setValue)
    {
        return SetIfDifferent(shouldSet, setValue);
    }

    public void OnPostGenerateGradleAndroidProject(string path)
    {
        string manifestPath = Path.Combine(path, GeneratedManifestRelativePath);
        if (!File.Exists(manifestPath))
        {
            throw new BuildFailedException($"{nameof(SUN_SV_AndroidARBuildValidator)} could not find generated AndroidManifest.xml at {manifestPath}.");
        }

        XmlDocument manifest = new XmlDocument();
        manifest.Load(manifestPath);

        XmlElement manifestElement = manifest.DocumentElement;
        XmlElement applicationElement = FindFirstChild(manifestElement, "application");
        List<string> errors = new List<string>();

        XmlElement cameraPermission = FindChildWithAndroidAttribute(manifestElement, "uses-permission", "name", AndroidPermissionCamera);
        if (cameraPermission == null)
        {
            errors.Add($"Missing <uses-permission android:name=\"{AndroidPermissionCamera}\">.");
        }

        XmlElement arCameraFeature = FindChildWithAndroidAttribute(manifestElement, "uses-feature", "name", AndroidHardwareCameraAr);
        if (arCameraFeature == null)
        {
            errors.Add($"Missing <uses-feature android:name=\"{AndroidHardwareCameraAr}\">.");
        }
        else if (GetAndroidAttribute(arCameraFeature, "required") != "true")
        {
            errors.Add($"<uses-feature android:name=\"{AndroidHardwareCameraAr}\"> must have android:required=\"true\".");
        }

        XmlElement arCoreMetaData = FindChildWithAndroidAttribute(applicationElement, "meta-data", "name", GoogleArCoreMetaDataName);
        if (arCoreMetaData == null)
        {
            errors.Add($"Missing <meta-data android:name=\"{GoogleArCoreMetaDataName}\">.");
        }
        else if (GetAndroidAttribute(arCoreMetaData, "value") != "required")
        {
            errors.Add($"<meta-data android:name=\"{GoogleArCoreMetaDataName}\"> must have android:value=\"required\".");
        }

        XmlElement skipPermissionsDialog = FindChildWithAndroidAttribute(applicationElement, "meta-data", "name", SkipPermissionsDialogMetaDataName);
        if (skipPermissionsDialog == null)
        {
            Debug.LogWarning($"{nameof(SUN_SV_AndroidARBuildValidator)} did not find unityplayer.SkipPermissionsDialog in the generated manifest. Runtime still requests Camera permission manually, but this differs from the ARCore build processor's expected manifest patch.");
        }

        if (errors.Count > 0)
        {
            throw new BuildFailedException(
                $"{nameof(SUN_SV_AndroidARBuildValidator)} blocked Android build because generated AndroidManifest.xml is missing AR camera requirements:\n- " +
                string.Join("\n- ", errors));
        }

        Debug.Log($"{nameof(SUN_SV_AndroidARBuildValidator)} verified generated AndroidManifest.xml contains CAMERA permission and ARCore Required metadata.");
    }

    private static void ValidateAndroidXRLoader(List<string> errors)
    {
        XRGeneralSettingsPerBuildTarget settingsPerBuildTarget =
            AssetDatabase.LoadAssetAtPath<XRGeneralSettingsPerBuildTarget>(XRGeneralSettingsPerBuildTargetPath);
        XRManagerSettings androidManager = settingsPerBuildTarget != null
            ? settingsPerBuildTarget.ManagerSettingsForBuildTarget(BuildTargetGroup.Android)
            : null;

        if (androidManager == null)
        {
            errors.Add("Android XR Manager Settings are missing.");
            return;
        }

        if (!androidManager.automaticLoading || !androidManager.automaticRunning)
        {
            errors.Add("Android XR Manager must use automatic Loading and Running for the ARCore camera subsystem.");
        }

        bool hasARCoreLoader = false;
        bool isARCoreFirst = false;
        for (int i = 0; i < androidManager.activeLoaders.Count; i++)
        {
            XRLoader loader = androidManager.activeLoaders[i];
            if (loader is ARCoreLoader)
            {
                hasARCoreLoader = true;
                isARCoreFirst = i == 0;
                break;
            }
        }

        if (!hasARCoreLoader)
        {
            errors.Add("Android XR Providers must include ARCoreLoader.");
        }
        else if (!isARCoreFirst)
        {
            errors.Add("ARCoreLoader should be the first Android XR Provider for this mobile AR prototype.");
        }
    }

    private static void ValidateARCoreSettings(List<string> errors)
    {
        ARCoreSettings arCoreSettings = ARCoreSettings.GetOrCreateSettings();
        if (arCoreSettings.requirement != ARCoreSettings.Requirement.Required)
        {
            errors.Add("ARCore Requirement must be Required so Android manifest generation writes com.google.ar.core=required and android.hardware.camera.ar.");
        }
    }

    private static void ValidateAndroidApplicationEntry(List<string> errors)
    {
        if (PlayerSettings.Android.applicationEntry != AndroidApplicationEntry.Activity)
        {
            errors.Add(
                "Android Application Entry Point must use Activity for this handheld ARCore prototype. " +
                "GameActivity can leave ARCore in SessionInitializing with a failed sensor queue and a null camera.");
        }
    }

    private static void ValidateAndroidGraphicsSettings(List<string> errors)
    {
        GraphicsDeviceType[] graphicsApis = PlayerSettings.GetGraphicsAPIs(BuildTarget.Android);
        bool hasOpenGles3 = false;
        for (int i = 0; i < graphicsApis.Length; i++)
        {
            if (graphicsApis[i] == GraphicsDeviceType.OpenGLES3)
            {
                hasOpenGles3 = true;
            }
        }

        if (!hasOpenGles3)
        {
            errors.Add("Android Graphics API list must include OpenGLES3 for the mobile AR camera feed.");
        }
        else if (graphicsApis.Length != 1 || graphicsApis[0] != GraphicsDeviceType.OpenGLES3)
        {
            errors.Add("Android Graphics API list must use OpenGLES3 only while validating the ARCore camera background on device.");
        }

        if (PlayerSettings.GetMobileMTRendering(NamedBuildTarget.Android))
        {
            errors.Add("Android Multithreaded Rendering must remain disabled while validating ARCore camera background rendering.");
        }

        if (PlayerSettings.graphicsJobs)
        {
            errors.Add("Graphics Jobs must remain disabled while validating ARCore camera background rendering.");
        }
    }

    private static void ValidateAndroidOrientationSettings(List<string> errors)
    {
        if (PlayerSettings.defaultInterfaceOrientation != UIOrientation.LandscapeLeft)
        {
            errors.Add("Default Orientation must be Landscape Left for the current Android AR camera validation pass.");
        }

        if (PlayerSettings.allowedAutorotateToPortrait
            || PlayerSettings.allowedAutorotateToPortraitUpsideDown
            || !PlayerSettings.allowedAutorotateToLandscapeLeft
            || PlayerSettings.allowedAutorotateToLandscapeRight)
        {
            errors.Add("Android autorotation must allow Landscape Left only while validating the ARCore camera background.");
        }
    }

    private static void ValidateMobileRenderPipelineAsset(List<string> errors)
    {
        UniversalRenderPipelineAsset pipelineAsset = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(MobileRenderPipelineAssetPath);
        if (pipelineAsset == null)
        {
            errors.Add($"Could not find mobile render pipeline asset at {MobileRenderPipelineAssetPath}.");
            return;
        }

        if (pipelineAsset.supportsHDR)
        {
            errors.Add("Mobile_RPAsset HDR must be disabled while validating Android AR camera background rendering.");
        }

        if (pipelineAsset.msaaSampleCount != 1)
        {
            errors.Add("Mobile_RPAsset MSAA must be Disabled (1 sample) while validating Android AR camera background rendering.");
        }

        if (!Mathf.Approximately(pipelineAsset.renderScale, 1.0f))
        {
            errors.Add("Mobile_RPAsset Render Scale must be 1.0 so the AR camera target matches the Android surface size.");
        }

        if (pipelineAsset.supportsCameraDepthTexture)
        {
            errors.Add("Mobile_RPAsset Depth Texture must be disabled for the AR camera background validation build.");
        }

        if (pipelineAsset.supportsCameraOpaqueTexture)
        {
            errors.Add("Mobile_RPAsset Opaque Texture must be disabled for the AR camera background validation build.");
        }
    }

    private static void ValidateMobileRendererFeatures(List<string> errors)
    {
        ScriptableRendererData rendererData = AssetDatabase.LoadAssetAtPath<ScriptableRendererData>(MobileRendererDataPath);
        if (rendererData == null)
        {
            errors.Add($"Could not find mobile renderer data at {MobileRendererDataPath}.");
            return;
        }

        if (!rendererData.TryGetRendererFeature<ARBackgroundRendererFeature>(out ARBackgroundRendererFeature backgroundFeature)
            || backgroundFeature == null
            || !backgroundFeature.isActive)
        {
            errors.Add("Mobile_Renderer must include an active ARBackgroundRendererFeature.");
        }

        if (!rendererData.TryGetRendererFeature<ARCommandBufferSupportRendererFeature>(out ARCommandBufferSupportRendererFeature commandBufferFeature)
            || commandBufferFeature == null
            || !commandBufferFeature.isActive)
        {
            errors.Add("Mobile_Renderer must include an active ARCommandBufferSupportRendererFeature.");
        }

        if (rendererData.useNativeRenderPass)
        {
            errors.Add("Mobile_Renderer Native Render Pass must remain disabled while validating AR camera background rendering.");
        }
    }

    private static void ValidateMobileARCameraSceneSettings(List<string> errors)
    {
        string scenePath = GetValidationScenePath();
        Scene alreadyLoadedScene = SceneManager.GetSceneByPath(scenePath);
        bool wasSceneAlreadyLoaded = alreadyLoadedScene.IsValid() && alreadyLoadedScene.isLoaded;
        Scene scene = wasSceneAlreadyLoaded ? alreadyLoadedScene : EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Additive);

        try
        {
            Camera arCamera = FindSceneCamera(scene, MainCameraName);
            if (arCamera == null)
            {
                errors.Add($"Could not find '{MainCameraName}' in {scenePath}.");
                return;
            }

            if (arCamera.targetTexture != null)
            {
                errors.Add("AR Main Camera must render directly to the Android surface, not to a target texture.");
            }

            if (arCamera.allowHDR)
            {
                errors.Add("AR Main Camera HDR must be disabled.");
            }

            if (arCamera.allowMSAA)
            {
                errors.Add("AR Main Camera MSAA must be disabled.");
            }

            if (arCamera.allowDynamicResolution)
            {
                errors.Add("AR Main Camera Dynamic Resolution must be disabled.");
            }

            if (!IsFullScreenRect(arCamera.rect))
            {
                errors.Add("AR Main Camera viewport must be fullscreen (0,0,1,1).");
            }

            ValidateUniversalAdditionalCameraData(arCamera, errors);
            CameraBackgroundRenderingMode expectedRenderMode = scenePath == StandardCameraTestScenePath
                ? CameraBackgroundRenderingMode.Any
                : CameraBackgroundRenderingMode.BeforeOpaques;
            ValidateARCameraComponents(arCamera, expectedRenderMode, errors);
        }
        finally
        {
            if (!wasSceneAlreadyLoaded && scene.IsValid())
            {
                EditorSceneManager.CloseScene(scene, true);
            }
        }
    }

    private static void ValidateUniversalAdditionalCameraData(Camera arCamera, List<string> errors)
    {
        UniversalAdditionalCameraData cameraData = arCamera.GetComponent<UniversalAdditionalCameraData>();
        if (cameraData == null)
        {
            errors.Add("AR Main Camera must include UniversalAdditionalCameraData.");
            return;
        }

        if (cameraData.renderType != CameraRenderType.Base)
        {
            errors.Add("AR Main Camera must be a URP Base camera.");
        }

        List<Camera> cameraStack = cameraData.cameraStack;
        if (cameraStack == null)
        {
            errors.Add("AR Main Camera renderer must support a Base camera stack contract, even though the stack remains empty.");
        }
        else if (cameraStack.Count > 0)
        {
            errors.Add("AR Main Camera camera stack must be empty while validating the ARCore camera background.");
        }

        if (cameraData.renderPostProcessing)
        {
            errors.Add("AR Main Camera Post Processing must be disabled to avoid Android render-pass attachment mismatches.");
        }

        if (cameraData.antialiasing != AntialiasingMode.None)
        {
            errors.Add("AR Main Camera URP anti-aliasing must be None.");
        }

        if (cameraData.allowHDROutput)
        {
            errors.Add("AR Main Camera HDR Output must be disabled.");
        }

        if (cameraData.requiresDepthTexture)
        {
            errors.Add("AR Main Camera Depth Texture override must be Off.");
        }

        if (cameraData.requiresColorTexture)
        {
            errors.Add("AR Main Camera Opaque Texture override must be Off.");
        }
    }

    private static void ValidateARCameraComponents(
        Camera arCamera,
        CameraBackgroundRenderingMode expectedRenderMode,
        List<string> errors)
    {
        ARCameraManager cameraManager = arCamera.GetComponent<ARCameraManager>();
        if (cameraManager == null)
        {
            errors.Add("AR Main Camera must include ARCameraManager.");
        }
        else
        {
            if (cameraManager.requestedBackgroundRenderingMode != expectedRenderMode)
            {
                errors.Add($"ARCameraManager background render mode must be {expectedRenderMode} for the active Android build scene.");
            }

            if (cameraManager.imageStabilizationRequested)
            {
                errors.Add("ARCameraManager Image Stabilization must remain disabled until the base camera feed is stable.");
            }
        }

        if (arCamera.GetComponent<ARCameraBackground>() == null)
        {
            errors.Add("AR Main Camera must include ARCameraBackground.");
        }
    }

    private static string GetValidationScenePath()
    {
        EditorBuildSettingsScene[] buildScenes = EditorBuildSettings.scenes;
        for (int i = 0; i < buildScenes.Length; i++)
        {
            if (buildScenes[i].enabled && !string.IsNullOrWhiteSpace(buildScenes[i].path))
            {
                return buildScenes[i].path;
            }
        }

        return FallbackScenePath;
    }

    private static Camera FindSceneCamera(Scene scene, string cameraName)
    {
        GameObject[] rootObjects = scene.GetRootGameObjects();
        for (int i = 0; i < rootObjects.Length; i++)
        {
            Camera camera = FindCameraRecursive(rootObjects[i].transform, cameraName);
            if (camera != null)
            {
                return camera;
            }
        }

        return null;
    }

    private static Camera FindCameraRecursive(Transform root, string cameraName)
    {
        if (root.name == cameraName && root.TryGetComponent(out Camera camera))
        {
            return camera;
        }

        for (int i = 0; i < root.childCount; i++)
        {
            Camera childCamera = FindCameraRecursive(root.GetChild(i), cameraName);
            if (childCamera != null)
            {
                return childCamera;
            }
        }

        return null;
    }

    private static bool IsFullScreenRect(Rect rect)
    {
        return Mathf.Approximately(rect.x, 0.0f)
            && Mathf.Approximately(rect.y, 0.0f)
            && Mathf.Approximately(rect.width, 1.0f)
            && Mathf.Approximately(rect.height, 1.0f);
    }

    private static XmlElement FindFirstChild(XmlElement parent, string elementName)
    {
        if (parent == null)
        {
            return null;
        }

        for (int i = 0; i < parent.ChildNodes.Count; i++)
        {
            if (parent.ChildNodes[i] is XmlElement element && element.LocalName == elementName)
            {
                return element;
            }
        }

        return null;
    }

    private static XmlElement FindChildWithAndroidAttribute(XmlElement parent, string elementName, string attributeName, string attributeValue)
    {
        if (parent == null)
        {
            return null;
        }

        for (int i = 0; i < parent.ChildNodes.Count; i++)
        {
            if (parent.ChildNodes[i] is not XmlElement element || element.LocalName != elementName)
            {
                continue;
            }

            if (GetAndroidAttribute(element, attributeName) == attributeValue)
            {
                return element;
            }
        }

        return null;
    }

    private static string GetAndroidAttribute(XmlElement element, string attributeName)
    {
        return element != null ? element.GetAttribute(attributeName, AndroidXmlNamespace) : string.Empty;
    }
}
